# Generated by Django 6.0.6 on 2026-06-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHoleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_visible', models.BooleanField(default=True, verbose_name='前台展示')),
            ],
            options={
                'verbose_name': '树洞留言',
                'verbose_name_plural': '树洞留言',
                'db_table': 'tree_hole_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
