# Generated by Django 6.0.6 on 2026-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(db_column='联系人', max_length=100, verbose_name='联系人')),
                ('gender', models.CharField(db_column='性别', max_length=20, verbose_name='性别')),
                ('hobbies', models.TextField(db_column='兴趣爱好', verbose_name='兴趣爱好')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
                'db_table': 'members',
            },
        ),
    ]
