# Generated by Django 6.0.6 on 2026-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.FileField(upload_to='class_photos/', verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_visible', models.BooleanField(default=True, verbose_name='前台展示')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'db_table': 'photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
